import { IndicatorDefinition } from '../types/data';

export const POPULAR_INDICATORS: IndicatorDefinition[] = [
  // 1. Digital & Tech Economy
  {
    id: 'IT.NET.USER.ZS',
    name: 'Individuals Using the Internet (% of population)',
    category: 'Digital Economy & Internet',
    unit: '% of population',
    unitSuffix: '%',
    description: 'Internet users are individuals who have used the Internet (from any location) in the last 3 months via computer, mobile phone, digital TV, games machine, etc.',
    source: 'International Telecommunication Union (ITU) via World Bank',
    sourceUrl: 'https://data.worldbank.org/indicator/IT.NET.USER.ZS',
    provider: 'World Bank',
    defaultCountryCode: 'WLD',
    featured: true,
    formatType: 'percent',
    tags: ['internet', 'digital', 'technology', 'users', 'online', 'connectivity', 'digital media', 'social media', 'content creation'],
    methodologyNote: 'Collected from national household surveys and official ITU administrative records.',
  },
  {
    id: 'IT.CEL.SETS.P2',
    name: 'Mobile Cellular Subscriptions (per 100 people)',
    category: 'Digital Economy & Internet',
    unit: 'Subscriptions per 100 people',
    description: 'Mobile cellular telephone subscriptions are subscriptions to a public mobile telephone service that provide access to the PSTN using cellular technology.',
    source: 'ITU World Telecommunication/ICT Indicators Database',
    sourceUrl: 'https://data.worldbank.org/indicator/IT.CEL.SETS.P2',
    provider: 'World Bank',
    defaultCountryCode: 'WLD',
    featured: true,
    formatType: 'decimal',
    tags: ['mobile', 'smartphones', 'cellular', 'telecom', 'devices', 'digital economy'],
  },
  {
    id: 'IT.NET.SECR.P6',
    name: 'Secure Internet Servers (per 1 Million People)',
    category: 'Technology & AI',
    unit: 'Servers per 1M people',
    description: 'Secure internet servers are servers using cryptographic protocols (e.g. TLS/SSL) in transactions over the internet, indicating cloud and digital infrastructure readiness.',
    source: 'Netcraft via World Bank',
    sourceUrl: 'https://data.worldbank.org/indicator/IT.NET.SECR.P6',
    provider: 'World Bank',
    defaultCountryCode: 'USA',
    featured: true,
    formatType: 'count',
    tags: ['cloud', 'ai infrastructure', 'servers', 'cybersecurity', 'cloud computing', 'datacenter'],
  },
  {
    id: 'GB.XPD.RSDV.GD.ZS',
    name: 'Research and Development Expenditure (% of GDP)',
    category: 'Technology & AI',
    unit: '% of GDP',
    unitSuffix: '%',
    description: 'Gross domestic expenditure on scientific research and experimental development (R&D) expressed as a percentage of GDP, a primary proxy for AI and high-tech innovation capacity.',
    source: 'UNESCO Institute for Statistics via World Bank',
    sourceUrl: 'https://data.worldbank.org/indicator/GB.XPD.RSDV.GD.ZS',
    provider: 'World Bank',
    defaultCountryCode: 'USA',
    featured: true,
    formatType: 'percent',
    tags: ['ai market', 'r&d', 'research', 'innovation', 'technology', 'artificial intelligence', 'science', 'patents'],
  },
  {
    id: 'TX.VAL.TECH.MF.ZS',
    name: 'High-Technology Exports (% of manufactured exports)',
    category: 'Technology & AI',
    unit: '% of manufactured exports',
    unitSuffix: '%',
    description: 'High-technology exports are products with high R&D intensity, such as in aerospace, computers, pharmaceuticals, scientific instruments, and electrical machinery.',
    source: 'UN COMTRADE database via World Bank',
    sourceUrl: 'https://data.worldbank.org/indicator/TX.VAL.TECH.MF.ZS',
    provider: 'World Bank',
    defaultCountryCode: 'CHN',
    featured: true,
    formatType: 'percent',
    tags: ['high tech', 'semiconductors', 'hardware', 'technology exports', 'electronics'],
  },
  {
    id: 'BX.GSR.CCIS.ZS',
    name: 'ICT Service Exports (% of service exports, BoP)',
    category: 'Digital Economy & Internet',
    unit: '% of service exports',
    unitSuffix: '%',
    description: 'Information and communication technology service exports include computer and communications services (telecommunications, software, digital content creation, data services).',
    source: 'International Monetary Fund, Balance of Payments Statistics Yearbook',
    sourceUrl: 'https://data.worldbank.org/indicator/BX.GSR.CCIS.ZS',
    provider: 'World Bank',
    defaultCountryCode: 'IND',
    featured: true,
    formatType: 'percent',
    tags: ['digital content creation', 'ict', 'software', 'digital services', 'saas', 'cloud services', 'e-commerce'],
  },

  // 2. Macroeconomics & GDP
  {
    id: 'NY.GDP.MKTP.CD',
    name: 'GDP (Current US$)',
    category: 'Macroeconomics & GDP',
    unit: 'Current US Dollars',
    unitPrefix: '$',
    description: 'Gross Domestic Product at purchaser prices is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products.',
    source: 'World Bank national accounts data, and OECD National Accounts data files',
    sourceUrl: 'https://data.worldbank.org/indicator/NY.GDP.MKTP.CD',
    provider: 'World Bank',
    defaultCountryCode: 'WLD',
    featured: true,
    formatType: 'currency',
    tags: ['gdp', 'economy', 'macroeconomics', 'market size', 'output', 'india gdp', 'us gdp', 'china gdp'],
  },
  {
    id: 'NY.GDP.PCAP.CD',
    name: 'GDP Per Capita (Current US$)',
    category: 'Macroeconomics & GDP',
    unit: 'Current US Dollars',
    unitPrefix: '$',
    description: 'GDP per capita is gross domestic product divided by midyear population, showing average economic output per resident.',
    source: 'World Bank national accounts data',
    sourceUrl: 'https://data.worldbank.org/indicator/NY.GDP.PCAP.CD',
    provider: 'World Bank',
    defaultCountryCode: 'USA',
    featured: true,
    formatType: 'currency',
    tags: ['gdp per capita', 'income', 'standard of living', 'economic development'],
  },
  {
    id: 'NY.GDP.MKTP.KD.ZG',
    name: 'GDP Growth (Annual %)',
    category: 'Macroeconomics & GDP',
    unit: 'Annual % Growth',
    unitSuffix: '%',
    description: 'Annual percentage growth rate of GDP at market prices based on constant local currency. Aggregates are based on constant 2015 U.S. dollars.',
    source: 'World Bank national accounts data',
    sourceUrl: 'https://data.worldbank.org/indicator/NY.GDP.MKTP.KD.ZG',
    provider: 'World Bank',
    defaultCountryCode: 'IND',
    featured: true,
    formatType: 'percent',
    tags: ['economic growth', 'gdp growth', 'expansion', 'recession', 'macro'],
  },
  {
    id: 'FP.CPI.TOTL.ZG',
    name: 'Inflation, Consumer Prices (Annual %)',
    category: 'Macroeconomics & GDP',
    unit: 'Annual %',
    unitSuffix: '%',
    description: 'Inflation as measured by the consumer price index reflects the annual percentage change in the cost to the average consumer of acquiring a basket of goods and services.',
    source: 'International Monetary Fund, International Financial Statistics',
    sourceUrl: 'https://data.worldbank.org/indicator/FP.CPI.TOTL.ZG',
    provider: 'World Bank',
    defaultCountryCode: 'USA',
    featured: true,
    formatType: 'percent',
    tags: ['inflation', 'cpi', 'prices', 'monetary', 'cost of living', 'macroeconomics'],
  },
  {
    id: 'SL.UEM.TOTL.ZS',
    name: 'Unemployment Rate (% of total labor force)',
    category: 'Education & Labor',
    unit: '% of labor force',
    unitSuffix: '%',
    description: 'Unemployment refers to the share of the labor force that is without work but available for and seeking employment (modeled ILO estimate).',
    source: 'International Labour Organization (ILOSTAT database)',
    sourceUrl: 'https://data.worldbank.org/indicator/SL.UEM.TOTL.ZS',
    provider: 'World Bank',
    defaultCountryCode: 'USA',
    featured: true,
    formatType: 'percent',
    tags: ['employment', 'unemployment', 'jobs', 'labor', 'workforce', 'hiring'],
  },

  // 3. Demographics & Population
  {
    id: 'SP.POP.TOTL',
    name: 'Population, Total',
    category: 'Demographics & Population',
    unit: 'People',
    description: 'Total population is based on the de facto definition of population, which counts all residents regardless of legal status or citizenship.',
    source: 'United Nations Population Division, World Population Prospects',
    sourceUrl: 'https://data.worldbank.org/indicator/SP.POP.TOTL',
    provider: 'World Bank',
    defaultCountryCode: 'WLD',
    featured: true,
    formatType: 'count',
    tags: ['population', 'global population', 'demographics', 'census', 'inhabitants', 'people'],
  },
  {
    id: 'SP.URB.TOTL.IN.ZS',
    name: 'Urban Population (% of total population)',
    category: 'Demographics & Population',
    unit: '% of total population',
    unitSuffix: '%',
    description: 'Urban population refers to people living in urban areas as defined by national statistical offices, key for consumer market expansion.',
    source: 'United Nations Population Division',
    sourceUrl: 'https://data.worldbank.org/indicator/SP.URB.TOTL.IN.ZS',
    provider: 'World Bank',
    defaultCountryCode: 'WLD',
    featured: false,
    formatType: 'percent',
    tags: ['urbanization', 'cities', 'demographics', 'urban population', 'smart cities'],
  },
  {
    id: 'SP.DYN.LE00.IN',
    name: 'Life Expectancy at Birth (Years)',
    category: 'Healthcare & Society',
    unit: 'Years',
    description: 'Life expectancy at birth indicates the number of years a newborn infant would live if prevailing patterns of mortality at the time of its birth were to stay the same throughout its life.',
    source: 'United Nations Population Division',
    sourceUrl: 'https://data.worldbank.org/indicator/SP.DYN.LE00.IN',
    provider: 'World Bank',
    defaultCountryCode: 'WLD',
    featured: false,
    formatType: 'decimal',
    tags: ['life expectancy', 'longevity', 'health', 'demographics'],
  },

  // 4. Energy & Environment
  {
    id: 'EG.ELC.RNEW.ZS',
    name: 'Renewable Electricity Output (% of total electricity output)',
    category: 'Energy & Environment',
    unit: '% of total electricity',
    unitSuffix: '%',
    description: 'Renewable electricity is the share of electricity generated by renewable power plants (hydro, solar, wind, geothermal, bioenergy) in total electricity generation.',
    source: 'IEA Statistics via World Bank',
    sourceUrl: 'https://data.worldbank.org/indicator/EG.ELC.RNEW.ZS',
    provider: 'World Bank',
    defaultCountryCode: 'WLD',
    featured: true,
    formatType: 'percent',
    tags: ['renewable energy', 'clean energy', 'solar', 'wind', 'electricity', 'green transition', 'electric vehicles', 'power'],
  },
  {
    id: 'EG.USE.ELEC.KH.PC',
    name: 'Electric Power Consumption (kWh per capita)',
    category: 'Energy & Environment',
    unit: 'kWh per capita',
    description: 'Electric power consumption measures the production of power plants and combined heat and power plants less transmission, distribution, and transformation losses.',
    source: 'IEA Statistics via World Bank',
    sourceUrl: 'https://data.worldbank.org/indicator/EG.USE.ELEC.KH.PC',
    provider: 'World Bank',
    defaultCountryCode: 'USA',
    featured: false,
    formatType: 'decimal',
    tags: ['electricity', 'energy consumption', 'power', 'datacenter power', 'ev charging'],
  },
  {
    id: 'EN.ATM.CO2E.PC',
    name: 'CO2 Emissions (Metric Tons Per Capita)',
    category: 'Energy & Environment',
    unit: 'Metric tons per capita',
    description: 'Carbon dioxide emissions are those stemming from the burning of fossil fuels and the manufacture of cement, divided by midyear population.',
    source: 'Climate Watch Data via World Bank',
    sourceUrl: 'https://data.worldbank.org/indicator/EN.ATM.CO2E.PC',
    provider: 'World Bank',
    defaultCountryCode: 'USA',
    featured: true,
    formatType: 'decimal',
    tags: ['co2', 'carbon', 'emissions', 'climate', 'environment', 'sustainability', 'greenhouse gas'],
  },

  // 5. Trade, Industry & Tourism
  {
    id: 'ST.INT.RCPT.CD',
    name: 'International Tourism, Receipts (Current US$)',
    category: 'Trade & Industry',
    unit: 'Current US Dollars',
    unitPrefix: '$',
    description: 'International tourism receipts are expenditures by international inbound visitors, including payments to national carriers for international transport.',
    source: 'World Tourism Organization (UNWTO) via World Bank',
    sourceUrl: 'https://data.worldbank.org/indicator/ST.INT.RCPT.CD',
    provider: 'World Bank',
    defaultCountryCode: 'USA',
    featured: true,
    formatType: 'currency',
    tags: ['tourism', 'travel', 'hospitality', 'international visitors', 'aviation', 'leisure'],
  },
  {
    id: 'NE.TRD.GNFS.ZS',
    name: 'Trade (% of GDP)',
    category: 'Trade & Industry',
    unit: '% of GDP',
    unitSuffix: '%',
    description: 'Trade is the sum of exports and imports of goods and services measured as a share of gross domestic product.',
    source: 'World Bank national accounts data',
    sourceUrl: 'https://data.worldbank.org/indicator/NE.TRD.GNFS.ZS',
    provider: 'World Bank',
    defaultCountryCode: 'DEU',
    featured: false,
    formatType: 'percent',
    tags: ['trade', 'globalization', 'exports', 'imports', 'commerce'],
  },
  {
    id: 'NV.IND.MANF.ZS',
    name: 'Manufacturing, Value Added (% of GDP)',
    category: 'Trade & Industry',
    unit: '% of GDP',
    unitSuffix: '%',
    description: 'Manufacturing refers to industries belonging to ISIC divisions 15-37. Value added is the net output of a sector after adding up all outputs and subtracting intermediate inputs.',
    source: 'World Bank national accounts data',
    sourceUrl: 'https://data.worldbank.org/indicator/NV.IND.MANF.ZS',
    provider: 'World Bank',
    defaultCountryCode: 'CHN',
    featured: false,
    formatType: 'percent',
    tags: ['manufacturing', 'industrial production', 'factory output', 'supply chain'],
  },

  // 6. Healthcare & Education
  {
    id: 'SH.XPD.CHEX.GD.ZS',
    name: 'Current Health Expenditure (% of GDP)',
    category: 'Healthcare & Society',
    unit: '% of GDP',
    unitSuffix: '%',
    description: 'Level of current health expenditure expressed as a percentage of GDP, indicating overall national healthcare spending and medical sector scale.',
    source: 'World Health Organization Global Health Expenditure database',
    sourceUrl: 'https://data.worldbank.org/indicator/SH.XPD.CHEX.GD.ZS',
    provider: 'World Bank',
    defaultCountryCode: 'USA',
    featured: true,
    formatType: 'percent',
    tags: ['healthcare', 'health expenditure', 'medical', 'pharma', 'biotech', 'hospitals'],
  },
  {
    id: 'SE.XPD.TOTL.GD.ZS',
    name: 'Government Expenditure on Education (% of GDP)',
    category: 'Education & Labor',
    unit: '% of GDP',
    unitSuffix: '%',
    description: 'General government expenditure on education (current, capital, and transfers) expressed as a percentage of GDP.',
    source: 'UNESCO Institute for Statistics',
    sourceUrl: 'https://data.worldbank.org/indicator/SE.XPD.TOTL.GD.ZS',
    provider: 'World Bank',
    defaultCountryCode: 'USA',
    featured: false,
    formatType: 'percent',
    tags: ['education', 'schools', 'universities', 'skills', 'edtech', 'human capital'],
  },
  {
    id: 'SE.TER.ENRR',
    name: 'School Enrollment, Tertiary (% gross)',
    category: 'Education & Labor',
    unit: '% Gross Enrollment',
    unitSuffix: '%',
    description: 'Total enrollment in tertiary education, regardless of age, expressed as a percentage of the total population in the official tertiary age group.',
    source: 'UNESCO Institute for Statistics',
    sourceUrl: 'https://data.worldbank.org/indicator/SE.TER.ENRR',
    provider: 'World Bank',
    defaultCountryCode: 'KOR',
    featured: false,
    formatType: 'percent',
    tags: ['higher education', 'tertiary education', 'graduates', 'stem', 'workforce skills'],
  }
];

export function findIndicatorById(id: string): IndicatorDefinition | undefined {
  return POPULAR_INDICATORS.find(ind => ind.id.toLowerCase() === id.toLowerCase());
}

export function searchIndicators(query: string, category?: string): IndicatorDefinition[] {
  const q = query.toLowerCase().trim();
  return POPULAR_INDICATORS.filter(ind => {
    const matchesCategory = !category || category === 'All' || ind.category === category;
    if (!matchesCategory) return false;
    if (!q) return true;
    
    return (
      ind.name.toLowerCase().includes(q) ||
      ind.id.toLowerCase().includes(q) ||
      ind.description.toLowerCase().includes(q) ||
      ind.tags.some(t => t.toLowerCase().includes(q))
    );
  });
}
